package creacionClases;

public class Animales {
    //LAS CLASES VAN EN MAYUSCULA
    //LA CREACION DE UNA CLASE VA EN MAYUSCULA
    //VA EN MAYUSCULA CUANDO SE CREA UNA CLASE Y ASI PODER LLAMARLA DESPUES EN OTRA CLASE
}
